### ISSUE TITLE
Quality Matters?!?!

### ISSUE THREAD

**Issue by lorr1** [hyparam/hylang#1]
As an ML practitioner, which I assume you are, it's common practice to post some numbers showing the quality of your language predictor over some dataset. Deep in a readme you have

```
return 'python' => 8.16% return 'markdown' => 13.32% one layer net => 91.45%
```

which hints at something but only after looking after hardcoded paths in your python (!!!) that I see it's starcoder data of some kind.

Would be helpful if this was more explicit. How do you compare against https://github.com/nitotm/efficient-language-detector-js or something similar?

Love the idea!

**Comment by platypii** [comment]
First of all, I'm not sure if you know anything about machine learning, but benchmarks are so easily gamed these days that requesting benchmark numbers really just shows how out of touch you are with modern deep learning. Maybe if you had asked for an ELO score versus a model I would take you more seriously.

And for the record, the repo you reference is a HUMAN language detector, not a programming language detector. Useless comparison!

But thank you for your interest, and kind words. Contributions are welcome (aka- :middle_finger:)

**Comment by lorr1** [comment]
...you must have not published to any AI conference in the last 5 years. Too bad.

![image](https://github.com/user-attachments/assets/d24632b2-dccc-4492-981a-4a629086114e)

**Comment by platypii** [comment]
Sorry I'm only the winner of the Classic Paper Award at the 2023 AAAI Conference :nail_care:

**Comment by lorr1** [comment]
(a) Not top 3 conference. (b) classic paper award...by definition was not a paper published recently.

My original statement stands

**Comment by platypii** [comment]
It was certainly top AI conference at the time! It's not my fault AAAI missed the entire deep learning boat, and are now resentful of the fact that they missed the only approach that actually has any hope of producing real AI :sob:

**Comment by lorr1** [comment]
"In your time"...and you are...how old? Agree with you there. But you also basically admitted to not being an AI scientist but rather a...comp linguist. Bag of words for you then. I bet that's how you build the language classifier, huh?

**Comment by platypii** [comment]
How dare you come into my repo and accuse me of being a Computational Linguist!? That's like the worst thing you could ever call someone. They spent decades thinking about this stuff, but never realized all they needed were more matmuls. So embarrassing.

But, like, yea... I did use a bag of words model :face_with_head_bandage:

**Comment by platypii** [comment]
Bag of Words is All You Need.

However, attention is all that @lorr1 needs.

**Comment by lorr1** [comment]
Learning the deep truth of oneself can be a humbling experience.

Linguists just weren't paying enough attention.

**Comment by lorr1** [comment]
> However, attention is all that @lorr1 needs.

So says the user with a the name "platypii" with an image of a black and purple flying squirrel man. Sure, I'm the one needing attention. You have what, 7 repos with the words "hyp" in front.

**Comment by platypii** [comment]
Stop distracting me from my important work of porting python libraries to javascript and prefixing them with hyp!
